DictTimeZone = {
    'Europe/Moscow':'3',
    'Europe/Astrakhan': '4',
    'Asia/Yekaterinburg': '5',
    'Asia/Aqtobe': '5',
    'Europe/Riga': '2',
    'Europe/Samara': '4',
    'Europe/Volgograd':'3',
    'Europe/Saratov':'4',
    'Europe/Kirov':'3',
    'Europe/Ulyanovsk':'4',
    'Europe/Kaliningrad':'2',
    'Europe/Kiev':'2',
    'Europe/Helsinki':'2',
    'Europe/Vilnius':'2',
    'Asia/Irkutsk':'8',
    'Europe/Minsk':'3',
    'Asia/Krasnoyarsk':'7',
    'Europe/Simferopol':'3',
    'Asia/Tbilisi':'4',
    'Europe/Zaporozhye':'2',
    'Europe/Oslo':'1',
    'Asia/Baku':'4',
    'Asia/Novosibirsk':'7',
    'Asia/Barnaul':'7',
    'Asia/Novokuznetsk':'7',
    'Asia/Omsk':'6',
    'Asia/Tomsk':'7',
    'Asia/Ulaanbaatar':'8',
    'Asia/Qyzylorda':'5',
    'Asia/Hovd':'7',
    'Asia/Chita':'9',
    'Asia/Yakutsk':'9',
    'Asia/Vladivostok':'10',
    'Asia/Sakhalin':'11',
    'Asia/Shanghai':'8',
    'Asia/Anadyr':'12',
    'Asia/Magadan':'11',
    'Asia/Khandyga':'9',
    'Asia/Kamchatka':'12',
    'Asia/Tokyo':'12',
    'Asia/Srednekolymsk':'11',
    'Asia/Ust-Nera':'10',
    'Asia/Ashgabat':'5',
    'Europe/Paris':'1',
    'Europe/Tallinn':'2',
    'Europe/Warsaw':'1',
    'Asia/Tashkent':'5',
    'Asia/Karachi':'5'
}
